'use client';
import { FormEvent, useEffect, useState } from 'react';
import { Bell, Globe2, Save } from 'lucide-react';
import { AppShell } from '@/components/app-shell';
import { api } from '@/lib/auth';
import { localeChangedEvent } from '@/lib/i18n';
type Settings = { locale:string; timezone:string; emailNotifications:boolean };
export default function SettingsPage(){
  const[form,setForm]=useState<Settings>({locale:'ru',timezone:'Asia/Qyzylorda',emailNotifications:true}),[message,setMessage]=useState(''),[error,setError]=useState('');
  useEffect(()=>{api<Settings>('/profile/preferences').then(setForm).catch(e=>setError(e.message))},[]);
  async function save(e:FormEvent){e.preventDefault();setError('');try{await api('/profile/preferences',{method:'PATCH',body:JSON.stringify(form)});localStorage.setItem('quality-hub-locale',form.locale);window.dispatchEvent(new Event(localeChangedEvent));setMessage('Настройки сохранены')}catch(reason){setError(reason instanceof Error?reason.message:'Ошибка')}}
  return <AppShell><main className="p-7 max-w-3xl mx-auto"><p className="text-muted text-sm m-0">Персонализация рабочего пространства</p><h1 className="text-3xl mt-1 mb-7">Настройки</h1>{message&&<p className="p-3 bg-green-50 text-green-700 rounded">{message}</p>}{error&&<p className="p-3 bg-red-50 text-red-700 rounded">{error}</p>}<form onSubmit={save} className="card glow-card p-8"><h2 className="flex gap-2 items-center"><Globe2 className="text-brand"/>Язык и регион</h2><label className="block text-sm font-semibold mb-2">Язык интерфейса</label><select className="field mb-6" value={form.locale} onChange={e=>setForm({...form,locale:e.target.value})}><option value="ru">Русский</option><option value="kk">Қазақша</option><option value="en">English</option></select><label className="block text-sm font-semibold mb-2">Часовой пояс</label><select className="field mb-8" value={form.timezone} onChange={e=>setForm({...form,timezone:e.target.value})}><option>Asia/Qyzylorda</option><option>Asia/Almaty</option><option>Asia/Astana</option><option>UTC</option><option>Europe/Moscow</option></select><h2 className="flex gap-2 items-center border-t border-[var(--line)] pt-7"><Bell className="text-brand"/>Уведомления</h2><label className="flex justify-between gap-4 p-5 bg-slate-50 rounded-xl cursor-pointer"><div><b>Уведомления по email</b><span className="block text-xs text-muted mt-2">Назначения, упоминания и результаты запусков</span></div><input type="checkbox" className="w-5" checked={form.emailNotifications} onChange={e=>setForm({...form,emailNotifications:e.target.checked})}/></label><button className="btn w-full mt-8 flex justify-center gap-2"><Save size={18}/>Сохранить настройки</button></form></main></AppShell>;
}
