import { BadRequestException, Injectable, NotFoundException, UnauthorizedException } from '@nestjs/common';
import * as argon2 from 'argon2';
import { mkdir, unlink, writeFile } from 'fs/promises';
import { randomUUID } from 'crypto';
import { createHash } from 'crypto';
import { resolve } from 'path';
import { PrismaService } from '../prisma/prisma.service';
import { RequestContext } from '../audit/request-context';
import { UpdatePreferencesDto } from './profile.dto';
@Injectable() export class ProfileService {
  constructor(private prisma: PrismaService) {}
  async preferences(userId:string,dto?:UpdatePreferencesDto,organizationId?:string){if(!dto)return this.prisma.user.findUnique({where:{id:userId},select:{locale:true,timezone:true,emailNotifications:true}});const previous=await this.prisma.user.findUnique({where:{id:userId},select:{locale:true,timezone:true,emailNotifications:true}});const updated=await this.prisma.user.update({where:{id:userId},data:dto,select:{locale:true,timezone:true,emailNotifications:true}});if(organizationId&&previous){const changes=Object.fromEntries(Object.entries(dto).filter(([key,value])=>previous[key as keyof typeof previous]!==value).map(([key,value])=>[key,{from:previous[key as keyof typeof previous],to:value}]));await this.prisma.auditLog.create({data:{organizationId,userId,action:'PREFERENCES_UPDATED',entityType:'USER',entityId:userId,metadata:{changes},ipAddress:RequestContext.ip()}});}return updated;}
  async sessions(userId:string,raw?:string){const currentHash=raw?createHash('sha256').update(raw).digest('hex'):null;const items=await this.prisma.refreshToken.findMany({where:{userId,revokedAt:null,expiresAt:{gt:new Date()}},select:{id:true,tokenHash:true,createdAt:true,expiresAt:true},orderBy:{createdAt:'desc'}});return items.map(({tokenHash,...item})=>({...item,isCurrent:tokenHash===currentHash}));}
  async revokeSession(userId:string,id:string,organizationId?:string,raw?:string){const token=await this.prisma.refreshToken.findFirst({where:{id,userId,revokedAt:null},select:{tokenHash:true}});const current=Boolean(token&&raw&&token.tokenHash===createHash('sha256').update(raw).digest('hex'));const result=await this.prisma.refreshToken.updateMany({where:{id,userId,revokedAt:null},data:{revokedAt:new Date()}});if(result.count&&organizationId)await this.prisma.auditLog.create({data:{organizationId,userId,action:'SESSION_REVOKED',entityType:'USER',entityId:userId,metadata:{sessionId:id},ipAddress:RequestContext.ip()}});return{success:result.count>0,current}}
  async get(organizationId: string, userId: string) { const member = await this.prisma.organizationMember.findUnique({ where: { organizationId_userId: { organizationId, userId } }, include: { organization: { select: { name: true } }, user: { select: { id: true, email: true, username: true, firstName: true, lastName: true, lastLoginAt: true, createdAt: true } } } }); if (!member) throw new NotFoundException('Профиль не найден'); const avatar = await this.prisma.attachment.findFirst({ where: { organizationId, entityType: 'USER_AVATAR', entityId: userId }, orderBy: { createdAt: 'desc' }, select: { id: true } }); return { ...member.user, role: member.role, organization: member.organization, avatarUrl: avatar ? `/profile/avatar/${avatar.id}` : null }; }
  async update(organizationId: string, userId: string, firstName: string, lastName: string) { const previous=await this.get(organizationId,userId);const next={firstName:firstName.trim(),lastName:lastName.trim()};const user=await this.prisma.user.update({where:{id:userId},data:next,select:{firstName:true,lastName:true}});const changes:Record<string,{from:string;to:string}>={};if(previous.firstName!==next.firstName)changes.firstName={from:previous.firstName,to:next.firstName};if(previous.lastName!==next.lastName)changes.lastName={from:previous.lastName,to:next.lastName};await this.prisma.auditLog.create({data:{organizationId,userId,action:'PROFILE_UPDATED',entityType:'USER',entityId:userId,metadata:{changes},ipAddress:RequestContext.ip()}});return user; }
  async password(organizationId: string, userId: string, current: string, next: string) { const user = await this.prisma.user.findUnique({ where: { id: userId } }); if (!user || !await argon2.verify(user.passwordHash, current)) throw new UnauthorizedException('Текущий пароль указан неверно'); await this.prisma.$transaction([this.prisma.user.update({ where: { id: userId }, data: { passwordHash: await argon2.hash(next) } }), this.prisma.refreshToken.updateMany({ where: { userId, revokedAt: null }, data: { revokedAt: new Date() } }), this.prisma.auditLog.create({ data: { organizationId, userId, action: 'PASSWORD_CHANGED', entityType: 'USER', entityId: userId, metadata:{changes:{password:{from:'скрыто',to:'изменён'}}}, ipAddress: RequestContext.ip() } })]); return { success: true }; }
  async upload(organizationId: string, userId: string, file?: { originalname: string; mimetype: string; size: number; buffer: Buffer }) { if (!file) throw new BadRequestException('Выберите изображение'); const extensions: Record<string, string> = { 'image/png': '.png', 'image/jpeg': '.jpg', 'image/webp': '.webp' }; if (!extensions[file.mimetype]) throw new BadRequestException('Разрешены PNG, JPG и WebP'); if (file.size > 5 * 1024 * 1024) throw new BadRequestException('Максимальный размер аватара — 5 МБ'); const old = await this.prisma.attachment.findMany({ where: { organizationId, entityType: 'USER_AVATAR', entityId: userId } }); const storageKey = `avatars/${randomUUID()}${extensions[file.mimetype]}`, root = process.env.UPLOAD_DIR ?? 'uploads'; await mkdir(resolve(root, 'avatars'), { recursive: true }); await writeFile(resolve(root, storageKey), file.buffer); const avatar = await this.prisma.$transaction(async tx => { await tx.attachment.deleteMany({ where: { id: { in: old.map(item => item.id) } } }); return tx.attachment.create({ data: { organizationId, entityType: 'USER_AVATAR', entityId: userId, fileName: file.originalname.slice(0, 255), mimeType: file.mimetype, size: file.size, storageKey, uploadedById: userId } }); }); await Promise.all(old.map(item => unlink(resolve(root, item.storageKey)).catch(() => undefined))); return { avatarUrl: `/profile/avatar/${avatar.id}` }; }
  async avatar(organizationId: string, id: string) { const item = await this.prisma.attachment.findFirst({ where: { id, organizationId, entityType: 'USER_AVATAR' } }); if (!item) throw new NotFoundException('Аватар не найден'); return { ...item, path: resolve(process.env.UPLOAD_DIR ?? 'uploads', item.storageKey) }; }
}
