import { BadRequestException, Injectable, NotFoundException, UnauthorizedException } from '@nestjs/common';
import * as argon2 from 'argon2';
import { mkdir, unlink, writeFile } from 'fs/promises';
import { randomUUID } from 'crypto';
import { resolve } from 'path';
import { PrismaService } from '../prisma/prisma.service';
import { RequestContext } from '../audit/request-context';
import { UpdatePreferencesDto } from './profile.dto';
@Injectable() export class ProfileService {
  constructor(private prisma: PrismaService) {}
  preferences(userId:string,dto?:UpdatePreferencesDto){return dto?this.prisma.user.update({where:{id:userId},data:dto,select:{locale:true,timezone:true,emailNotifications:true}}):this.prisma.user.findUnique({where:{id:userId},select:{locale:true,timezone:true,emailNotifications:true}})}
  sessions(userId:string){return this.prisma.refreshToken.findMany({where:{userId,revokedAt:null,expiresAt:{gt:new Date()}},select:{id:true,createdAt:true,expiresAt:true},orderBy:{createdAt:'desc'}})}
  async revokeSession(userId:string,id:string){await this.prisma.refreshToken.updateMany({where:{id,userId,revokedAt:null},data:{revokedAt:new Date()}});return{success:true}}
  async get(organizationId: string, userId: string) { const member = await this.prisma.organizationMember.findUnique({ where: { organizationId_userId: { organizationId, userId } }, include: { organization: { select: { name: true } }, user: { select: { id: true, email: true, username: true, firstName: true, lastName: true, lastLoginAt: true, createdAt: true } } } }); if (!member) throw new NotFoundException('Профиль не найден'); const avatar = await this.prisma.attachment.findFirst({ where: { organizationId, entityType: 'USER_AVATAR', entityId: userId }, orderBy: { createdAt: 'desc' }, select: { id: true } }); return { ...member.user, role: member.role, organization: member.organization, avatarUrl: avatar ? `/profile/avatar/${avatar.id}` : null }; }
  async update(organizationId: string, userId: string, firstName: string, lastName: string) { await this.get(organizationId, userId); const user = await this.prisma.user.update({ where: { id: userId }, data: { firstName: firstName.trim(), lastName: lastName.trim() }, select: { firstName: true, lastName: true } }); await this.prisma.auditLog.create({ data: { organizationId, userId, action: 'PROFILE_UPDATED', entityType: 'USER', entityId: userId, ipAddress: RequestContext.ip() } }); return user; }
  async password(organizationId: string, userId: string, current: string, next: string) { const user = await this.prisma.user.findUnique({ where: { id: userId } }); if (!user || !await argon2.verify(user.passwordHash, current)) throw new UnauthorizedException('Текущий пароль указан неверно'); await this.prisma.$transaction([this.prisma.user.update({ where: { id: userId }, data: { passwordHash: await argon2.hash(next) } }), this.prisma.refreshToken.updateMany({ where: { userId, revokedAt: null }, data: { revokedAt: new Date() } }), this.prisma.auditLog.create({ data: { organizationId, userId, action: 'PASSWORD_CHANGED', entityType: 'USER', entityId: userId, ipAddress: RequestContext.ip() } })]); return { success: true }; }
  async upload(organizationId: string, userId: string, file?: { originalname: string; mimetype: string; size: number; buffer: Buffer }) { if (!file) throw new BadRequestException('Выберите изображение'); const extensions: Record<string, string> = { 'image/png': '.png', 'image/jpeg': '.jpg', 'image/webp': '.webp' }; if (!extensions[file.mimetype]) throw new BadRequestException('Разрешены PNG, JPG и WebP'); if (file.size > 5 * 1024 * 1024) throw new BadRequestException('Максимальный размер аватара — 5 МБ'); const old = await this.prisma.attachment.findMany({ where: { organizationId, entityType: 'USER_AVATAR', entityId: userId } }); const storageKey = `avatars/${randomUUID()}${extensions[file.mimetype]}`, root = process.env.UPLOAD_DIR ?? 'uploads'; await mkdir(resolve(root, 'avatars'), { recursive: true }); await writeFile(resolve(root, storageKey), file.buffer); const avatar = await this.prisma.$transaction(async tx => { await tx.attachment.deleteMany({ where: { id: { in: old.map(item => item.id) } } }); return tx.attachment.create({ data: { organizationId, entityType: 'USER_AVATAR', entityId: userId, fileName: file.originalname.slice(0, 255), mimeType: file.mimetype, size: file.size, storageKey, uploadedById: userId } }); }); await Promise.all(old.map(item => unlink(resolve(root, item.storageKey)).catch(() => undefined))); return { avatarUrl: `/profile/avatar/${avatar.id}` }; }
  async avatar(organizationId: string, id: string) { const item = await this.prisma.attachment.findFirst({ where: { id, organizationId, entityType: 'USER_AVATAR' } }); if (!item) throw new NotFoundException('Аватар не найден'); return { ...item, path: resolve(process.env.UPLOAD_DIR ?? 'uploads', item.storageKey) }; }
}
