import{BadRequestException,Injectable,NotFoundException}from'@nestjs/common';import{Prisma}from'@prisma/client';import{PrismaService}from'../prisma/prisma.service';import{CreateDefectDto,DefectQueryDto,UpdateDefectDto}from'./defects.dto';
@Injectable()export class DefectsService{constructor(private prisma:PrismaService){}
async list(org:string,q:DefectQueryDto){const where:Prisma.DefectWhereInput={project:{organizationId:org},...(q.projectId?{projectId:q.projectId}:{}),...(q.status?{status:q.status}:{}),...(q.priority?{priority:q.priority}:{}),...(q.severity?{severity:q.severity}:{}),...(q.search?.trim()?{OR:[{title:{contains:q.search.trim(),mode:'insensitive'}},...(/^\d+$/.test(q.search.trim())?[{defectNumber:Number(q.search.trim())}]:[])]}:{})};const[items,total]=await this.prisma.$transaction([this.prisma.defect.findMany({where,orderBy:{createdAt:'desc'},skip:(q.page-1)*q.pageSize,take:q.pageSize,include:{project:{select:{code:true,name:true}},testRun:{select:{id:true,name:true}},testCase:{select:{id:true,caseNumber:true,title:true}}}}),this.prisma.defect.count({where})]);return{items:items.map(x=>this.present(x)),meta:{page:q.page,pageSize:q.pageSize,total,totalPages:Math.max(1,Math.ceil(total/q.pageSize))}}}
async get(org:string,id:string){const x=await this.prisma.defect.findFirst({where:{id,project:{organizationId:org}},include:{project:{select:{code:true,name:true}},testRun:{select:{id:true,name:true}},testCase:{select:{id:true,caseNumber:true,title:true}}}});if(!x)throw new NotFoundException('Дефект не найден');return this.present(x)}
async create(org:string,userId:string,d:CreateDefectDto){await this.validate(org,d);return this.prisma.$transaction(async tx=>{const p=await tx.project.update({where:{id:d.projectId},data:{nextDefectNumber:{increment:1}},select:{nextDefectNumber:true}});return tx.defect.create({data:{...this.data(d),title:d.title.trim(),projectId:d.projectId,reporterId:userId,defectNumber:p.nextDefectNumber-1}})})}
async update(org:string,id:string,d:UpdateDefectDto){const current=await this.get(org,id);await this.validate(org,{...d,projectId:d.projectId??current.projectId}as CreateDefectDto);return this.prisma.defect.update({where:{id},data:this.data(d)})}
async remove(org:string,id:string){await this.get(org,id);await this.prisma.defect.delete({where:{id}});return{success:true}}
private present(x:any){return{...x,displayId:`${x.project.code}-BUG-${String(x.defectNumber).padStart(4,'0')}`,testCase:x.testCase?{...x.testCase,displayId:`${x.project.code}-TC-${String(x.testCase.caseNumber).padStart(4,'0')}`}:null}}
private data(d:UpdateDefectDto){return{...(d.title!==undefined?{title:d.title.trim()}:{}),...(d.description!==undefined?{description:d.description.trim()||null}:{}),...(d.stepsToReproduce!==undefined?{stepsToReproduce:d.stepsToReproduce.trim()||null}:{}),...(d.expectedResult!==undefined?{expectedResult:d.expectedResult.trim()||null}:{}),...(d.actualResult!==undefined?{actualResult:d.actualResult.trim()||null}:{}),...(d.environment!==undefined?{environment:d.environment.trim()||null}:{}),...(d.build!==undefined?{build:d.build.trim()||null}:{}),...(d.status?{status:d.status}:{}),...(d.priority?{priority:d.priority}:{}),...(d.severity?{severity:d.severity}:{}),...(d.assigneeId!==undefined?{assigneeId:d.assigneeId||null}:{}),...(d.testRunId!==undefined?{testRunId:d.testRunId||null}:{}),...(d.testCaseId!==undefined?{testCaseId:d.testCaseId||null}:{}),...(d.runCaseId!==undefined?{runCaseId:d.runCaseId||null}:{})}}
private async validate(org:string,d:CreateDefectDto){const p=await this.prisma.project.findFirst({where:{id:d.projectId,organizationId:org}});if(!p)throw new NotFoundException('Проект не найден');if(d.assigneeId&&!await this.prisma.organizationMember.findUnique({where:{organizationId_userId:{organizationId:org,userId:d.assigneeId}}}))throw new BadRequestException('Исполнитель не состоит в организации');if(d.runCaseId&&!await this.prisma.testRunCase.findFirst({where:{id:d.runCaseId,testRun:{projectId:d.projectId,project:{organizationId:org}}}}))throw new BadRequestException('Тест из запуска не найден')}
}
