'use client';
import { useEffect, useState } from 'react';
import { KeyRound, LogOut, MonitorSmartphone } from 'lucide-react';
import { api, session } from '@/lib/auth';
import { notify } from '@/components/toast-viewport';
type SessionItem={id:string;createdAt:string;expiresAt:string;isCurrent:boolean};
export function SessionManager(){
  const[items,setItems]=useState<SessionItem[]>([]),[busy,setBusy]=useState(''),[error,setError]=useState('');
  async function load(){try{const[list,current]=await Promise.all([api<SessionItem[]>('/profile/sessions'),api<{id:string|null}>('/auth/current-session')]);setItems(list.map(item=>({...item,isCurrent:item.id===current.id})));setError('')}catch(reason){setError(reason instanceof Error?reason.message:'Не удалось загрузить сессии')}}
  useEffect(()=>{void load()},[]);
  async function revoke(item:SessionItem){setBusy(item.id);setError('');try{const result=await api<{success:boolean}>(`/profile/sessions/${item.id}`,{method:'DELETE'});if(!result.success)throw new Error('Сессия уже завершена');if(item.isCurrent){await fetch('/api/auth/logout',{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:'{}'});session.clear();location.replace('/');return}setItems(current=>current.filter(value=>value.id!==item.id));notify('Сессия завершена')}catch(reason){const message=reason instanceof Error?reason.message:'Не удалось завершить сессию';setError(message);notify(message,'error')}finally{setBusy('')}}
  return <section className="card p-5 mt-5"><div className="flex gap-3 items-center mb-3"><span className="p-2.5 bg-indigo-50 text-brand rounded-xl"><KeyRound size={20}/></span><div><h2 className="m-0 text-lg">Активные сессии</h2><span className="block text-xs text-muted">Завершите неизвестные или старые входы</span></div></div>{error&&<p className="p-3 bg-red-50 text-red-700 rounded-lg text-sm">{error}</p>}<div className="max-h-64 overflow-y-auto pr-1">{items.map(item=><div className="flex flex-wrap justify-between items-center gap-3 py-3 border-t border-[var(--line)]" key={item.id}><div className="flex gap-3 items-center min-w-0"><MonitorSmartphone className="text-muted shrink-0" size={19}/><div className="min-w-0"><b className="text-sm">{item.isCurrent?'Текущая сессия':'Другая сессия'}</b><span className="block text-[11px] text-muted truncate">Создана {new Date(item.createdAt).toLocaleString('ru-RU')} · до {new Date(item.expiresAt).toLocaleDateString('ru-RU')}</span></div></div><button type="button" className="btn-secondary text-red-600 flex gap-2 items-center py-2" disabled={Boolean(busy)} onClick={()=>revoke(item)}><LogOut size={15}/>{busy===item.id?'Завершение…':'Завершить'}</button></div>)}{!items.length&&!error&&<p className="text-muted text-center py-5 text-sm">Активных сессий нет</p>}</div></section>;
}
