'use client';
import { useEffect, useMemo, useRef, useState } from 'react';
import Link from 'next/link';
import { Bell, CheckCheck, Search, X } from 'lucide-react';
import { api } from '@/lib/auth';

type Result = { type: string; id: string; title: string; subtitle: string; url: string };
type Notice = { id: string; title: string; body: string; url: string | null; isRead: boolean; createdAt: string };
const names: Record<string, string> = { PROJECT: 'Проекты', TEST_CASE: 'Тест-кейсы', TEST_PLAN: 'Тест-планы', TEST_RUN: 'Тест-раны', DEFECT: 'Дефекты', REQUIREMENT: 'Требования' };
function Highlight({ text, query }: { text: string; query: string }) { const i = text.toLowerCase().indexOf(query.toLowerCase()); return i < 0 ? text : <>{text.slice(0, i)}<mark className="bg-amber-200 text-current rounded px-0.5">{text.slice(i, i + query.length)}</mark>{text.slice(i + query.length)}</>; }

export function WorkspaceTools() {
  const [searchOpen, setSearchOpen] = useState(false), [noticeOpen, setNoticeOpen] = useState(false), [query, setQuery] = useState(''), [results, setResults] = useState<Result[]>([]), [notices, setNotices] = useState<Notice[]>([]), [active, setActive] = useState(0);
  const input = useRef<HTMLInputElement>(null); const grouped = useMemo(() => Object.entries(results.reduce<Record<string, Result[]>>((all, item) => ({ ...all, [item.type]: [...(all[item.type] ?? []), item] }), {})), [results]);
  function load() { api<Notice[]>('/workspace/notifications').then(setNotices).catch(() => undefined); }
  useEffect(load, []);
  useEffect(() => { const fn = (event: KeyboardEvent) => { if ((event.ctrlKey || event.metaKey) && event.key.toLowerCase() === 'k') { event.preventDefault(); setSearchOpen(true); } }; addEventListener('keydown', fn); return () => removeEventListener('keydown', fn); }, []);
  useEffect(() => { if (searchOpen) setTimeout(() => input.current?.focus(), 40); }, [searchOpen]);
  useEffect(() => { setActive(0); if (query.trim().length < 2) { setResults([]); return; } const timer = setTimeout(() => api<Result[]>(`/workspace/search?q=${encodeURIComponent(query)}`).then(setResults), 220); return () => clearTimeout(timer); }, [query]);
  async function readAll() { await api('/workspace/notifications/read-all', { method: 'PATCH' }); load(); }
  async function read(notice: Notice) { if (!notice.isRead) await api(`/workspace/notifications/${notice.id}/read`, { method: 'PATCH' }); setNoticeOpen(false); load(); }
  function key(event: React.KeyboardEvent) { if (event.key === 'ArrowDown') { event.preventDefault(); setActive(v => Math.min(results.length - 1, v + 1)); } if (event.key === 'ArrowUp') { event.preventDefault(); setActive(v => Math.max(0, v - 1)); } if (event.key === 'Enter' && results[active]) location.href = results[active].url; if (event.key === 'Escape') setSearchOpen(false); }
  const unread = notices.filter(item => !item.isRead).length;
  return <>
    <div className="fixed right-52 top-3 z-40 flex gap-2"><button className="hidden xl:flex items-center gap-2 px-3 h-10 rounded-lg border border-[var(--line)] bg-[var(--panel)] text-muted cursor-pointer" onClick={() => setSearchOpen(true)}><Search size={16}/><span className="text-xs">Поиск</span><kbd className="text-[10px] bg-slate-100 rounded px-1.5">Ctrl K</kbd></button><div className="relative"><button className="icon-btn h-10 w-10 bg-[var(--panel)] relative" onClick={() => setNoticeOpen(!noticeOpen)}><Bell size={19}/>{unread > 0 && <span className="absolute -right-1 -top-1 min-w-4 h-4 rounded-full bg-red-500 text-white text-[9px]">{unread}</span>}</button>{noticeOpen && <div className="absolute right-0 top-12 w-96 max-w-[85vw] card overflow-hidden shadow-2xl"><div className="p-4 flex justify-between border-b border-[var(--line)]"><b>Уведомления</b><button className="text-xs text-brand border-0 bg-transparent cursor-pointer" onClick={readAll}><CheckCheck size={14} className="inline"/> Прочитать все</button></div><div className="max-h-96 overflow-y-auto">{notices.map(notice => notice.url ? <Link href={notice.url} onClick={() => read(notice)} className={`block p-4 border-b border-[var(--line)] text-current no-underline hover:bg-slate-50 ${notice.isRead ? '' : 'bg-indigo-50/50'}`} key={notice.id}><b className="text-sm">{notice.title}</b><p className="text-xs text-muted my-1">{notice.body}</p><span className="text-[10px] text-muted">{new Date(notice.createdAt).toLocaleString('ru-RU')}</span></Link> : <div className={`p-4 border-b border-[var(--line)] ${notice.isRead ? '' : 'bg-indigo-50/50'}`} key={notice.id}><b className="text-sm">{notice.title}</b><p className="text-xs text-muted my-1">{notice.body}</p></div>)}{!notices.length && <p className="p-10 text-center text-muted text-sm">Уведомлений нет</p>}</div></div>}</div></div>
    {searchOpen && <div className="fixed inset-0 bg-slate-950/60 backdrop-blur-sm z-[70] flex justify-center pt-[10vh] px-4" onMouseDown={event => { if (event.target === event.currentTarget) setSearchOpen(false); }}><section className="card w-full max-w-2xl h-fit max-h-[75vh] overflow-hidden shadow-2xl"><div className="relative border-b border-[var(--line)]"><Search className="absolute left-5 top-5 text-muted"/><input ref={input} onKeyDown={key} className="w-full border-0 bg-transparent py-5 pl-14 pr-14 text-lg outline-none" placeholder="Найти кейс, дефект, требование, план…" value={query} onChange={event => setQuery(event.target.value)}/><button className="icon-btn absolute right-3 top-3" onClick={() => setSearchOpen(false)}><X/></button></div><div className="max-h-[55vh] overflow-y-auto p-2">{grouped.map(([type, items]) => <section key={type}><h3 className="text-[10px] uppercase tracking-widest text-muted px-3 mt-3 mb-1">{names[type]}</h3>{items?.map(item => { const index = results.indexOf(item); return <Link href={item.url} onMouseEnter={() => setActive(index)} onClick={() => setSearchOpen(false)} className={`flex justify-between p-3 rounded-lg text-current no-underline ${active === index ? 'bg-indigo-50 text-brand' : 'hover:bg-slate-50'}`} key={`${item.type}-${item.id}`}><div><b className="text-sm"><Highlight text={item.title} query={query}/></b><span className="block text-xs text-muted"><Highlight text={item.subtitle} query={query}/></span></div><span className="text-[10px] text-brand bg-indigo-50 rounded-full px-2 py-1 h-fit">{names[item.type]}</span></Link>; })}</section>)}{query.length >= 2 && !results.length && <p className="p-10 text-center text-muted">Ничего не найдено</p>}{query.length < 2 && <p className="p-10 text-center text-muted">Введите минимум два символа</p>}</div></section></div>}
  </>;
}
