'use client';

import { FormEvent, useCallback, useEffect, useState } from 'react';
import { useParams, useRouter } from 'next/navigation';
import { ArrowLeft, Clock3, History, RotateCcw, Save } from 'lucide-react';
import { AppShell } from '@/components/app-shell';
import { api, session } from '@/lib/auth';
import { EditableStep, StepSectionEditor } from '@/components/step-section-editor';

type VersionStep = EditableStep & { id: string; position: number; section: 'PRECONDITION' | 'ACTION' | 'POSTCONDITION' };
type Version = { id: string; version: number; description: string | null; durationSeconds: number; preconditions: string | null; postconditions: string | null; createdAt: string; steps: VersionStep[] };
type Detail = { id: string; displayId: string; title: string; status: string; priority: string; severity: string; type: string; currentVersion: number; project: { code: string; name: string }; folder: { id: string; name: string } | null; versions: Version[]; currentVersionData: Version };
type Editor = { title: string; status: string; priority: string; type: string; description: string; durationSeconds: number; preconditionSteps: EditableStep[]; steps: EditableStep[]; postconditionSteps: EditableStep[]; createNewVersion: boolean };

export default function TestCaseEditor() {
  const { id } = useParams<{ id: string }>(); const router = useRouter(); const [detail, setDetail] = useState<Detail | null>(null); const [form, setForm] = useState<Editor | null>(null);
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(''); const [saved, setSaved] = useState(''); const [compare, setCompare] = useState<Version | null>(null);
  const role = session.get()?.user.role; const canEdit = ['ADMIN', 'QA_LEAD', 'QA_ENGINEER'].includes(role ?? '');

  const load = useCallback(async () => { setLoading(true); try { const value = await api<Detail>(`/test-cases/${id}`); setDetail(value); const version = value.currentVersionData; const bySection = (section: VersionStep['section']) => version?.steps.filter(step => step.section === section).map(({ action, expectedResult }) => ({ action, expectedResult })) ?? []; setForm({ title: value.title, status: value.status, priority: value.priority, type: value.type, description: version?.description ?? '', durationSeconds: version?.durationSeconds ?? 0, preconditionSteps: bySection('PRECONDITION'), steps: bySection('ACTION'), postconditionSteps: bySection('POSTCONDITION'), createNewVersion: false }); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Не удалось загрузить тест-кейс'); } finally { setLoading(false); } }, [id]);
  useEffect(() => { load(); }, [load]);

  async function submit(event: FormEvent) { event.preventDefault(); if (!form) return; setSaving(true); setError(''); setSaved(''); try { await api(`/test-cases/${id}/save`, { method: 'POST', body: JSON.stringify(form) }); setSaved(form.createNewVersion ? 'Новая версия создана' : 'Изменения сохранены'); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Не удалось сохранить'); } finally { setSaving(false); } }
  async function restore(version: number) { if (!confirm(`Восстановить содержимое версии v${version} как новую версию?`)) return; try { await api(`/test-cases/${id}/versions/${version}/restore`, { method: 'POST' }); setCompare(null); await load(); setSaved(`Версия v${version} восстановлена`); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Ошибка восстановления'); } }
  const setDuration = (part: 'h' | 'm' | 's', value: number) => setForm(current => { if (!current) return current; const h = Math.floor(current.durationSeconds / 3600), m = Math.floor(current.durationSeconds % 3600 / 60), s = current.durationSeconds % 60; return { ...current, durationSeconds: (part === 'h' ? value : h) * 3600 + (part === 'm' ? value : m) * 60 + (part === 's' ? value : s) }; });

  if (loading) return <AppShell><div className="p-10 text-muted">Загрузка редактора…</div></AppShell>;
  if (!detail || !form) return <AppShell><div className="p-10 text-red-700">{error || 'Тест-кейс не найден'}</div></AppShell>;
  const hours = Math.floor(form.durationSeconds / 3600), minutes = Math.floor(form.durationSeconds % 3600 / 60), seconds = form.durationSeconds % 60;
  const changed = compare ? { description: compare.description !== form.description, duration: compare.durationSeconds !== form.durationSeconds, preconditions: JSON.stringify(compare.steps.filter(step => step.section === 'PRECONDITION')) !== JSON.stringify(form.preconditionSteps), actions: JSON.stringify(compare.steps.filter(step => step.section === 'ACTION')) !== JSON.stringify(form.steps), postconditions: JSON.stringify(compare.steps.filter(step => step.section === 'POSTCONDITION')) !== JSON.stringify(form.postconditionSteps) } : null;

  return <AppShell><form onSubmit={submit}><main className="p-7 max-w-[1500px] mx-auto"><div className="flex justify-between gap-4 mb-6"><div className="flex gap-3 items-start"><button type="button" className="icon-btn" onClick={() => router.push('/test-cases')}><ArrowLeft /></button><div><p className="text-brand font-semibold text-sm m-0">{detail.displayId} · {detail.project.name}</p><h1 className="text-2xl m-0 mt-1">{detail.title}</h1></div></div>{canEdit && <button className="btn flex gap-2 items-center" disabled={saving}><Save size={18} />{saving ? 'Сохранение…' : 'Сохранить'}</button>}</div>
    {error && <p className="p-3 bg-red-50 text-red-700 rounded-lg">{error}</p>}{saved && <p className="p-3 bg-green-50 text-green-700 rounded-lg">{saved}</p>}
    <div className="grid grid-cols-[minmax(0,1fr)_310px] gap-5"><div className="space-y-5"><section className="card p-6"><h2 className="mt-0 text-lg">Основные данные</h2><label className="block text-sm font-semibold mb-2">Название</label><input className="field mb-4" disabled={!canEdit} value={form.title} onChange={event => setForm({ ...form, title: event.target.value })} required minLength={2} /><div className="grid grid-cols-3 gap-3"><select className="field" disabled={!canEdit} value={form.status} onChange={event => setForm({ ...form, status: event.target.value })}><option value="DRAFT">Черновик</option><option value="READY">Готов</option><option value="NEEDS_UPDATE">Требует обновления</option><option value="OBSOLETE">Устарел</option></select><select className="field" disabled={!canEdit} value={form.priority} onChange={event => setForm({ ...form, priority: event.target.value })}><option value="HIGHEST">Самый высокий</option><option value="HIGH">Высокий</option><option value="MEDIUM">Средний</option><option value="LOW">Низкий</option><option value="LOWEST">Очень низкий</option></select><select className="field" disabled={!canEdit} value={form.type} onChange={event => setForm({ ...form, type: event.target.value })}><option>FUNCTIONAL</option><option>UI</option><option>API</option><option>SECURITY</option><option>PERFORMANCE</option><option>REGRESSION</option><option>SMOKE</option><option>INTEGRATION</option></select></div></section>
      <section className="card p-6"><h2 className="mt-0 text-lg">Описание и продолжительность</h2><label className="block text-sm font-semibold mb-2">Описание</label><textarea className="field min-h-24 mb-4" disabled={!canEdit} value={form.description} onChange={event => setForm({ ...form, description: event.target.value })} /><div><label className="block text-sm font-semibold mb-2"><Clock3 size={15} className="inline" /> Продолжительность</label><div className="flex gap-2 items-center"><input className="field w-20" type="number" min={0} disabled={!canEdit} value={hours} onChange={event => setDuration('h', Number(event.target.value))} /><span>ч</span><input className="field w-20" type="number" min={0} max={59} disabled={!canEdit} value={minutes} onChange={event => setDuration('m', Number(event.target.value))} /><span>м</span><input className="field w-20" type="number" min={0} max={59} disabled={!canEdit} value={seconds} onChange={event => setDuration('s', Number(event.target.value))} /><span>с</span></div></div></section>
      <section className="card p-6 space-y-4"><h2 className="mt-0 text-lg">Структура тест-кейса</h2><StepSectionEditor title="Шаги предусловий" hint="Подготовка данных, окружения и начального состояния." steps={form.preconditionSteps} onChange={preconditionSteps => setForm({ ...form, preconditionSteps })} disabled={!canEdit} /><StepSectionEditor title="Основные шаги выполнения" hint="Действия тестировщика и ожидаемые результаты." steps={form.steps} onChange={steps => setForm({ ...form, steps })} disabled={!canEdit} /><StepSectionEditor title="Шаги постусловий" hint="Проверки и восстановление состояния после теста." steps={form.postconditionSteps} onChange={postconditionSteps => setForm({ ...form, postconditionSteps })} disabled={!canEdit} /></section></div>
      <aside className="space-y-5"><section className="card p-5"><h2 className="mt-0 text-lg">Версионирование</h2><div className="flex items-center gap-2 mb-4"><History className="text-brand" /><b>Текущая версия: v{detail.currentVersion}</b></div>{canEdit && <label className="flex gap-2 items-start text-sm"><input type="checkbox" checked={form.createNewVersion} onChange={event => setForm({ ...form, createNewVersion: event.target.checked })} /><span>Создать новую версию при сохранении</span></label>}<div className="border-t border-[var(--line)] mt-4 pt-3 space-y-2">{detail.versions.map(version => <div key={version.id} className="p-3 rounded-lg bg-slate-50"><div className="flex justify-between"><b>v{version.version}</b><span className="text-xs text-muted">{new Date(version.createdAt).toLocaleString('ru-RU')}</span></div><div className="flex gap-1 mt-2"><button type="button" className="btn-secondary text-xs p-2" onClick={() => setCompare(version)}>Сравнить</button>{canEdit && version.version !== detail.currentVersion && <button type="button" className="icon-btn" title="Восстановить" onClick={() => restore(version.version)}><RotateCcw size={15} /></button>}</div></div>)}</div></section>
        {compare && <section className="card p-5"><div className="flex justify-between"><h2 className="m-0 text-lg">v{compare.version} ↔ текущая</h2><button type="button" className="icon-btn" onClick={() => setCompare(null)}>×</button></div><div className="space-y-2 mt-4 text-sm">{Object.entries(changed ?? {}).map(([name, value]) => <div key={name} className={`p-2 rounded ${value ? 'bg-amber-50 text-amber-800' : 'bg-green-50 text-green-700'}`}>{name}: {value ? 'изменено' : 'без изменений'}</div>)}</div></section>}
      </aside></div></main></form></AppShell>;
}
