'use client';
import { FormEvent, useEffect, useMemo, useState } from 'react';
import { Activity, Bell, Building2, ChevronRight, CircleUserRound, Database, FileClock, LayoutDashboard, LogOut, Moon, Pencil, Plus, Search, Server, ShieldCheck, Sun, UserCog, Users, X } from 'lucide-react';
import { adminApi, adminSession } from '@/lib/auth';
type Tab='overview'|'organizations'|'users'|'activity'|'admin-audit'|'profile';
type Stats={organizations:number;users:number;activeUsers:number;blockedUsers:number;auditEvents:number;recentLogins:number;roles:Record<string,number>;health:{database:string;api:string}};
type Member={role:string;createdAt:string;user:{id:string;email:string;username:string;firstName:string;lastName:string;isActive:boolean;lastLoginAt:string|null;createdAt:string}};
type Org={id:string;name:string;slug:string;isActive:boolean;createdAt:string;updatedAt:string;_count:{members:number;projects:number;auditLogs:number};members?:Member[]};
type User={id:string;email:string;username:string;firstName:string;lastName:string;isActive:boolean;isSystemAdmin:boolean;lastLoginAt:string|null;createdAt:string;memberships:Array<{role:string;organization:{id:string;name:string}}>};
type Audit={id:string;action:string;entityType:string|null;entityId:string|null;ipAddress:string|null;createdAt:string;metadata:any;user:{firstName:string;lastName:string;email:string}|null;organization:{name:string}|null};
type Profile={id:string;email:string;username:string;firstName:string;lastName:string;lastLoginAt:string|null;createdAt:string};
const roles:Record<string,string>={ADMIN:'Администратор организации',QA_LEAD:'QA Lead',QA_ENGINEER:'QA Engineer',DEVELOPER:'Разработчик',VIEWER:'Наблюдатель'};
const actionLabels:Record<string,string>={LOGIN_SUCCESS:'Вход в систему',SYSTEM_USER_CREATED:'Создан пользователь',SYSTEM_USER_UPDATED:'Изменён пользователь',ORGANIZATION_CREATED:'Создана организация',ORGANIZATION_UPDATED:'Изменена организация',ORGANIZATION_DEACTIVATED:'Организация приостановлена',SYSTEM_PROFILE_UPDATED:'Изменён профиль администратора'};
const emptyUser={email:'',username:'',firstName:'',lastName:'',password:'',organizationId:'',role:'QA_ENGINEER'};
function initials(first='',last=''){return `${first[0]??''}${last[0]??''}`.toUpperCase()||'SA'}
function Changes({value}:{value:any}){const changes=value?.changes;if(!changes||typeof changes!=='object')return <span className="muted">Нет подробностей</span>;return <div className="changes">{Object.entries(changes).map(([key,v]:any)=><span key={key}><b>{key}</b>: {String(v?.from??'—')} → {String(v?.to??'—')}</span>)}</div>}
function Modal({title,onClose,children}:{title:string;onClose:()=>void;children:React.ReactNode}){return <div className="overlay" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><section className="modal"><header><div><span className="eyebrow">SYSTEM ADMIN</span><h2>{title}</h2></div><button className="icon" onClick={onClose}><X/></button></header>{children}</section></div>}
export default function AdminPortal(){
 const[ready,setReady]=useState(false),[logged,setLogged]=useState(false),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[tab,setTab]=useState<Tab>('overview'),[dark,setDark]=useState(false),[stats,setStats]=useState<Stats|null>(null),[orgs,setOrgs]=useState<Org[]>([]),[users,setUsers]=useState<User[]>([]),[audit,setAudit]=useState<Audit[]>([]),[adminAudit,setAdminAudit]=useState<Audit[]>([]),[profile,setProfile]=useState<Profile|null>(null),[search,setSearch]=useState(''),[modal,setModal]=useState<'org'|'user'|'editUser'|'profile'|null>(null),[selectedOrg,setSelectedOrg]=useState<Org|null>(null),[selectedUser,setSelectedUser]=useState<User|null>(null),[orgForm,setOrgForm]=useState({name:'',slug:''}),[userForm,setUserForm]=useState(emptyUser);
 useEffect(()=>{setLogged(Boolean(adminSession.get()?.user.systemAdmin));setDark(localStorage.getItem('qh-admin-theme')==='dark');setReady(true)},[]);
 async function load(){try{const[s,o,u,a,aa,p]=await Promise.all([adminApi<Stats>('/system-admin/stats'),adminApi<Org[]>('/system-admin/organizations'),adminApi<User[]>('/system-admin/users'),adminApi<Audit[]>('/system-admin/audit'),adminApi<Audit[]>('/system-admin/admin-audit'),adminApi<Profile>('/system-admin/profile')]);setStats(s);setOrgs(o);setUsers(u);setAudit(a);setAdminAudit(aa);setProfile(p);setUserForm(v=>({...v,organizationId:v.organizationId||o[0]?.id||''}))}catch(e){setError((e as Error).message)}}
 useEffect(()=>{if(logged)void load()},[logged]);
 function ok(message:string){setNotice(message);setError('');setTimeout(()=>setNotice(''),3000)}
 async function login(e:FormEvent){e.preventDefault();setError('');try{const r=await fetch('/api/auth/login',{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password})}),data=await r.json();if(!r.ok)throw new Error(data?.message??'Ошибка входа');adminSession.set(data);setLogged(true)}catch(x){setError((x as Error).message)}}
 async function logout(){await fetch('/api/auth/logout',{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:'{}'});adminSession.clear();setLogged(false)}
 async function saveOrg(e:FormEvent){e.preventDefault();try{if(selectedOrg)await adminApi(`/system-admin/organizations/${selectedOrg.id}`,{method:'PATCH',body:JSON.stringify(orgForm)});else await adminApi('/system-admin/organizations',{method:'POST',body:JSON.stringify(orgForm)});setModal(null);setSelectedOrg(null);setOrgForm({name:'',slug:''});await load();ok('Организация сохранена')}catch(x){setError((x as Error).message)}}
 async function openOrg(org:Org){try{setSelectedOrg(await adminApi<Org>(`/system-admin/organizations/${org.id}`))}catch(x){setError((x as Error).message)}}
 async function deactivateOrg(){if(!selectedOrg)return;try{await adminApi(`/system-admin/organizations/${selectedOrg.id}`,{method:'DELETE'});setSelectedOrg(null);await load();ok('Организация приостановлена')}catch(x){setError((x as Error).message)}}
 async function saveUser(e:FormEvent){e.preventDefault();try{if(selectedUser)await adminApi(`/system-admin/users/${selectedUser.id}`,{method:'PATCH',body:JSON.stringify({firstName:userForm.firstName,lastName:userForm.lastName,organizationId:userForm.organizationId,role:userForm.role})});else await adminApi('/system-admin/users',{method:'POST',body:JSON.stringify(userForm)});setModal(null);setSelectedUser(null);setUserForm({...emptyUser,organizationId:orgs[0]?.id??''});await load();ok('Пользователь сохранён')}catch(x){setError((x as Error).message)}}
 async function toggleUser(user:User){try{await adminApi(`/system-admin/users/${user.id}`,{method:'PATCH',body:JSON.stringify({isActive:!user.isActive})});await load();ok(user.isActive?'Доступ пользователя приостановлен':'Доступ пользователя восстановлен')}catch(x){setError((x as Error).message)}}
 async function saveProfile(e:FormEvent){e.preventDefault();try{const p=await adminApi<Profile>('/system-admin/profile',{method:'PATCH',body:JSON.stringify({firstName:profile?.firstName,lastName:profile?.lastName})});setProfile(p);setModal(null);ok('Профиль обновлён');await load()}catch(x){setError((x as Error).message)}}
 const filteredUsers=useMemo(()=>users.filter(u=>`${u.firstName} ${u.lastName} ${u.email} ${u.username}`.toLowerCase().includes(search.toLowerCase())),[users,search]);
 const filteredOrgs=useMemo(()=>orgs.filter(o=>`${o.name} ${o.slug}`.toLowerCase().includes(search.toLowerCase())),[orgs,search]);
 if(!ready)return null;
 if(!logged)return <main className="login"><div className="login-orb one"/><div className="login-orb two"/><form onSubmit={login} className="login-card"><div className="brand-mark"><ShieldCheck/></div><span className="eyebrow">QUALITY HUB • SYSTEM CONTROL</span><h1>Центр администрирования</h1><p className="muted">Защищённый контур управления платформой</p><label>Email администратора<input className="field" type="email" placeholder="name@company.com" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Пароль<input className="field" type="password" placeholder="Введите пароль" value={password} onChange={e=>setPassword(e.target.value)} required minLength={8}/></label>{error&&<p className="alert error">{error}</p>}<button className="btn wide">Войти в систему</button><small>© 2026 Almen Alnur • All rights reserved</small></form></main>;
 const nav:Array<[Tab,string,any,string]>=[['overview','Обзор',LayoutDashboard,'Состояние платформы'],['organizations','Организации',Building2,'Структура клиентов'],['users','Пользователи',Users,'Учётные записи'],['activity','Активность',Activity,'Действия пользователей'],['admin-audit','Журнал админки',FileClock,'Изменения администратора'],['profile','Мой профиль',CircleUserRound,'Личные данные']];
 const title=nav.find(n=>n[0]===tab);
 return <div className={dark?'admin dark':'admin'}><aside><div className="logo"><span><ShieldCheck/></span><div>Quality Hub<b>Administration</b></div></div><nav>{nav.map(([id,label,Icon,desc])=><button className={tab===id?'active':''} onClick={()=>{setTab(id);setSelectedOrg(null)}} key={id}><Icon/><span>{label}<small>{desc}</small></span><ChevronRight/></button>)}</nav><div className="aside-foot"><button onClick={logout}><LogOut/>Выйти</button><small>© 2026 Almen Alnur<br/>Owner & developer</small></div></aside><div className="workspace"><header className="topbar"><div><span className="eyebrow">SYSTEM ADMINISTRATION</span><b>{title?.[1]}</b></div><div className="top-actions"><button className="icon" title="Уведомления"><Bell/></button><button className="icon" onClick={()=>{setDark(!dark);localStorage.setItem('qh-admin-theme',!dark?'dark':'light')}}>{dark?<Sun/>:<Moon/>}</button><button className="profile-chip" onClick={()=>setTab('profile')}><span>{initials(profile?.firstName,profile?.lastName)}</span><div><b>{profile?.firstName} {profile?.lastName}</b><small>Системный администратор</small></div></button></div></header><main><div className="page-head"><div><p>{title?.[3]}</p><h1>{title?.[1]}</h1></div>{(tab==='organizations'||tab==='users')&&<button className="btn" onClick={()=>{setSelectedUser(null);setSelectedOrg(null);setOrgForm({name:'',slug:''});setUserForm({...emptyUser,organizationId:orgs[0]?.id??''});setModal(tab==='organizations'?'org':'user')}}><Plus/>Создать</button>}</div>{error&&<div className="alert error">{error}<button onClick={()=>setError('')}>×</button></div>}{notice&&<div className="toast"><ShieldCheck/>{notice}</div>}
 {tab==='overview'&&<><section className="metrics">{[[Building2,'Организации',stats?.organizations,'Всего контуров'],[Users,'Пользователи',stats?.users,`${stats?.activeUsers??0} активных`],[UserCog,'Заблокированы',stats?.blockedUsers,'Требуют внимания'],[Activity,'Входы за 7 дней',stats?.recentLogins,'Активность системы']].map(([Icon,label,value,hint]:any)=><article className="metric" key={label}><div className="metric-icon"><Icon/></div><p>{label}</p><strong>{value??'—'}</strong><small>{hint}</small></article>)}</section><section className="overview-grid"><article className="panel"><div className="panel-title"><div><h2>Распределение ролей</h2><p>Все участники организаций</p></div><Users/></div><div className="role-bars">{Object.entries(roles).map(([key,label])=>{const count=stats?.roles[key]??0,total=Object.values(stats?.roles??{}).reduce((a,b)=>a+b,0);return <div key={key}><span>{label}<b>{count}</b></span><i><em style={{width:`${total?count/total*100:0}%`}}/></i></div>})}</div></article><article className="panel"><div className="panel-title"><div><h2>Состояние сервисов</h2><p>Текущая доступность платформы</p></div><Server/></div><div className="health"><div><span><Database/>PostgreSQL</span><b><i/>Работает</b></div><div><span><Server/>Backend API</span><b><i/>Работает</b></div><div><span><ShieldCheck/>Контроль доступа</span><b><i/>Защищён</b></div></div></article></section></>}
 {(tab==='organizations'||tab==='users')&&<div className="toolbar"><Search/><input placeholder={tab==='organizations'?'Найти организацию':'Найти пользователя'} value={search} onChange={e=>setSearch(e.target.value)}/><span>{tab==='organizations'?filteredOrgs.length:filteredUsers.length} записей</span></div>}
 {tab==='organizations'&&!selectedOrg&&<section className="org-grid">{filteredOrgs.map(org=><article className="org-card" key={org.id} onClick={()=>openOrg(org)}><div className="org-icon"><Building2/></div><div className="org-title"><h3>{org.name}</h3><code>{org.slug}</code></div><div className="org-stats"><span><b>{org._count.members}</b>Участников</span><span><b>{org._count.projects}</b>Проектов</span><span><b>{org._count.auditLogs}</b>Событий</span></div><footer><small>Создана {new Date(org.createdAt).toLocaleDateString('ru-RU')}</small><ChevronRight/></footer></article>)}</section>}
 {tab==='organizations'&&selectedOrg&&<section><button className="back" onClick={()=>setSelectedOrg(null)}>← Все организации</button><article className="org-detail panel"><div className="org-detail-head"><div className="org-icon"><Building2/></div><div><h2>{selectedOrg.name}</h2><code>{selectedOrg.slug}</code></div><button className="btn-secondary" onClick={()=>{setOrgForm({name:selectedOrg.name,slug:selectedOrg.slug});setModal('org')}}><Pencil/>Редактировать</button></div><div className="detail-meta"><span>Создана <b>{new Date(selectedOrg.createdAt).toLocaleString('ru-RU')}</b></span><span>Участников <b>{selectedOrg._count.members}</b></span><span>Проектов <b>{selectedOrg._count.projects}</b></span></div></article><div className="panel table-panel"><div className="panel-title"><div><h2>Участники организации</h2><p>Подробные данные и состояние доступа</p></div></div><table><thead><tr><th>Пользователь</th><th>Роль</th><th>Последний вход</th><th>Добавлен</th><th>Статус</th></tr></thead><tbody>{selectedOrg.members?.map(m=><tr key={m.user.id}><td><div className="user-cell"><span>{initials(m.user.firstName,m.user.lastName)}</span><div><b>{m.user.firstName} {m.user.lastName}</b><small>{m.user.email} • @{m.user.username}</small></div></div></td><td>{roles[m.role]}</td><td>{m.user.lastLoginAt?new Date(m.user.lastLoginAt).toLocaleString('ru-RU'):'Не входил'}</td><td>{new Date(m.createdAt).toLocaleDateString('ru-RU')}</td><td><i className={m.user.isActive?'status on':'status'}>{m.user.isActive?'Активен':'Отключён'}</i></td></tr>)}</tbody></table></div></section>}
 {tab==='users'&&<section className="panel table-panel"><table><thead><tr><th>Пользователь</th><th>Организация</th><th>Роль</th><th>Последний вход</th><th>Статус</th><th/></tr></thead><tbody>{filteredUsers.map(user=>{const m=user.memberships[0];return <tr key={user.id}><td><div className="user-cell"><span>{initials(user.firstName,user.lastName)}</span><div><b>{user.firstName} {user.lastName}{user.isSystemAdmin&&<em>System</em>}</b><small>{user.email} • @{user.username}</small></div></div></td><td>{m?.organization.name??'—'}</td><td>{roles[m?.role]??m?.role}</td><td>{user.lastLoginAt?new Date(user.lastLoginAt).toLocaleString('ru-RU'):'Не входил'}</td><td><i className={user.isActive?'status on':'status'}>{user.isActive?'Активен':'Отключён'}</i></td><td><div className="row-actions"><button className="icon" disabled={user.isSystemAdmin} onClick={()=>{setSelectedUser(user);setUserForm({...emptyUser,firstName:user.firstName,lastName:user.lastName,organizationId:m?.organization.id??'',role:m?.role??'VIEWER'});setModal('editUser')}}><Pencil/></button><button className="btn-secondary" disabled={user.isSystemAdmin} onClick={()=>toggleUser(user)}>{user.isActive?'Отключить':'Активировать'}</button></div></td></tr>})}</tbody></table></section>}
 {(tab==='activity'||tab==='admin-audit')&&<AuditTable items={tab==='activity'?audit:adminAudit} admin={tab==='admin-audit'}/>}
 {tab==='profile'&&profile&&<section className="profile-layout"><article className="profile-card panel"><div className="avatar-xl">{initials(profile.firstName,profile.lastName)}</div><h2>{profile.firstName} {profile.lastName}</h2><p>{profile.email}</p><i className="status on">Системный администратор</i><button className="btn" onClick={()=>setModal('profile')}><Pencil/>Редактировать профиль</button></article><article className="panel profile-info"><h2>Данные учётной записи</h2><dl><div><dt>Имя пользователя</dt><dd>@{profile.username}</dd></div><div><dt>Email</dt><dd>{profile.email}</dd></div><div><dt>Последний вход</dt><dd>{profile.lastLoginAt?new Date(profile.lastLoginAt).toLocaleString('ru-RU'):'—'}</dd></div><div><dt>Дата создания</dt><dd>{new Date(profile.createdAt).toLocaleDateString('ru-RU')}</dd></div></dl></article></section>}
 </main></div>
 {modal==='org'&&<Modal title={selectedOrg?'Редактировать организацию':'Новая организация'} onClose={()=>setModal(null)}><form className="form" onSubmit={saveOrg}><label>Название<input className="field" value={orgForm.name} onChange={e=>setOrgForm({...orgForm,name:e.target.value})} placeholder="Например, Acme QA" required/></label><label>Уникальный slug<input className="field" value={orgForm.slug} onChange={e=>setOrgForm({...orgForm,slug:e.target.value.toLowerCase().replace(/[^a-z0-9-]/g,'-')})} placeholder="acme-qa" required/></label><div className="form-actions"><button type="button" className="btn-secondary" onClick={()=>setModal(null)}>Отмена</button><button className="btn">Сохранить</button></div></form></Modal>}
 {(modal==='user'||modal==='editUser')&&<Modal title={selectedUser?'Редактирование пользователя':'Новый пользователь'} onClose={()=>setModal(null)}><form className="form two" onSubmit={saveUser}>{!selectedUser&&<><label>Email<input className="field" type="email" value={userForm.email} onChange={e=>setUserForm({...userForm,email:e.target.value})} required/></label><label>Логин<input className="field" value={userForm.username} onChange={e=>setUserForm({...userForm,username:e.target.value})} required/></label></>}<label>Имя<input className="field" value={userForm.firstName} onChange={e=>setUserForm({...userForm,firstName:e.target.value})} required/></label><label>Фамилия<input className="field" value={userForm.lastName} onChange={e=>setUserForm({...userForm,lastName:e.target.value})} required/></label>{!selectedUser&&<label className="full">Временный пароль<input className="field" type="password" minLength={8} value={userForm.password} onChange={e=>setUserForm({...userForm,password:e.target.value})} required/></label>}<label>Организация<select className="field" value={userForm.organizationId} onChange={e=>setUserForm({...userForm,organizationId:e.target.value})}>{orgs.map(o=><option value={o.id} key={o.id}>{o.name}</option>)}</select></label><label>Роль<select className="field" value={userForm.role} onChange={e=>setUserForm({...userForm,role:e.target.value})}>{Object.entries(roles).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label><div className="form-actions full"><button type="button" className="btn-secondary" onClick={()=>setModal(null)}>Отмена</button><button className="btn">Сохранить</button></div></form></Modal>}
 {modal==='profile'&&profile&&<Modal title="Редактировать профиль" onClose={()=>setModal(null)}><form className="form two" onSubmit={saveProfile}><label>Имя<input className="field" value={profile.firstName} onChange={e=>setProfile({...profile,firstName:e.target.value})}/></label><label>Фамилия<input className="field" value={profile.lastName} onChange={e=>setProfile({...profile,lastName:e.target.value})}/></label><div className="form-actions full"><button type="button" className="btn-secondary" onClick={()=>setModal(null)}>Отмена</button><button className="btn">Сохранить</button></div></form></Modal>}
 </div>}
function AuditTable({items,admin}:{items:Audit[];admin:boolean}){const[q,setQ]=useState('');const data=items.filter(i=>`${i.action} ${i.user?.email} ${i.organization?.name} ${i.ipAddress}`.toLowerCase().includes(q.toLowerCase()));return <><div className="toolbar"><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Поиск по действию, пользователю, IP или организации"/><span>{data.length} событий</span></div><section className="panel table-panel"><table><thead><tr><th>Дата и время</th><th>{admin?'Администратор':'Пользователь'}</th><th>IP</th><th>Объект</th><th>Действие</th><th>Что изменилось</th></tr></thead><tbody>{data.map(i=><tr key={i.id}><td>{new Date(i.createdAt).toLocaleString('ru-RU')}</td><td><b>{i.user?`${i.user.firstName} ${i.user.lastName}`:'Система'}</b><small className="block">{i.user?.email}</small></td><td><code>{i.ipAddress??'—'}</code></td><td>{i.entityType??'—'}<small className="block">{i.organization?.name}</small></td><td><span className="action-badge">{actionLabels[i.action]??i.action}</span></td><td><Changes value={i.metadata}/></td></tr>)}</tbody></table></section></>}
