'use client';

import { useCallback, useEffect, useState } from 'react'; import { useParams, useRouter } from 'next/navigation'; import Link from 'next/link'; import { ArrowLeft, Plus, Trash2, X } from 'lucide-react';
import { AppShell } from '@/components/app-shell'; import { api, session } from '@/lib/auth';
type Case = { id: string; displayId: string; title: string; status: string; priority: string; type: string };
type Plan = { id: string; name: string; description: string | null; projectId: string; environment: string | null; build: string | null; version: string | null; startsAt: string | null; endsAt: string | null; project: { code: string; name: string }; cases: Array<{ position: number; testCase: Case }>; _count: { runs: number } };
type FolderItem = { id: string; name: string; parentId: string | null };
const priorityLabels: Record<string, string> = { HIGHEST: 'Самый высокий', HIGH: 'Высокий', MEDIUM: 'Средний', LOW: 'Низкий', LOWEST: 'Очень низкий' };
export default function TestPlanDetail() {
  const { id } = useParams<{ id: string }>(); const router = useRouter(); const [plan, setPlan] = useState<Plan | null>(null); const [available, setAvailable] = useState<Case[]>([]); const [folders, setFolders] = useState<FolderItem[]>([]); const [selected, setSelected] = useState<string[]>([]); const [folderId, setFolderId] = useState(''); const [priority, setPriority] = useState(''); const [modal, setModal] = useState(false); const [error, setError] = useState(''); const role = session.get()?.user.role; const canManage = role === 'ADMIN' || role === 'QA_LEAD';
  const load = useCallback(async () => { try { const value = await api<Plan>(`/test-plans/${id}`); setPlan(value); const [cases, folderItems] = await Promise.all([api<{ items: Case[] }>(`/projects/${value.projectId}/test-cases?page=1&pageSize=100`), api<FolderItem[]>(`/projects/${value.projectId}/test-case-folders`)]); const used = new Set(value.cases.map(entry => entry.testCase.id)); setAvailable(cases.items.filter(item => !used.has(item.id))); setFolders(folderItems); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Ошибка загрузки'); } }, [id]);
  useEffect(() => { load(); }, [load]);
  async function add() { const body: Record<string, unknown> = {}; if (selected.length) body.testCaseIds = selected; if (folderId) body.folderId = folderId; if (priority) body.priority = priority; try { await api(`/test-plans/${id}/cases`, { method: 'POST', body: JSON.stringify(body) }); setModal(false); setSelected([]); setFolderId(''); setPriority(''); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Ошибка добавления'); } }
  async function remove(testCaseId: string) { try { await api(`/test-plans/${id}/cases/${testCaseId}`, { method: 'DELETE' }); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Ошибка удаления'); } }
  if (!plan) return <AppShell><div className="p-10">{error || 'Загрузка…'}</div></AppShell>;
  return <AppShell><main className="p-7 max-w-7xl mx-auto"><div className="flex justify-between mb-6"><div className="flex gap-3"><button className="icon-btn" onClick={() => router.push('/test-plans')}><ArrowLeft /></button><div><p className="text-brand text-sm font-semibold m-0">{plan.project.code} · Тест-план</p><h1 className="text-3xl m-0 mt-1">{plan.name}</h1></div></div><div className="flex gap-2"><Link className="btn-secondary no-underline" href={`/reports/test-plans/${plan.id}`}>Открыть отчёт</Link>{canManage && <button className="btn flex gap-2 items-center" onClick={() => setModal(true)}><Plus size={18} />Добавить тесты</button>}</div></div>{error && <p className="p-3 bg-red-50 text-red-700 rounded-lg">{error}</p>}
    <section className="card p-5 mb-5"><div className="grid grid-cols-5 gap-4 text-sm"><div><span className="text-muted">Период</span><b className="block mt-1">{plan.startsAt ? new Date(plan.startsAt).toLocaleDateString('ru-RU') : '—'} — {plan.endsAt ? new Date(plan.endsAt).toLocaleDateString('ru-RU') : '—'}</b></div><div><span className="text-muted">Environment</span><b className="block mt-1">{plan.environment || '—'}</b></div><div><span className="text-muted">Build</span><b className="block mt-1">{plan.build || '—'}</b></div><div><span className="text-muted">Version</span><b className="block mt-1">{plan.version || '—'}</b></div><div><span className="text-muted">Test Runs</span><b className="block mt-1">{plan._count.runs}</b></div></div>{plan.description && <p className="text-muted mb-0">{plan.description}</p>}</section>
    <section className="card overflow-hidden"><div className="p-4 border-b border-[var(--line)]"><b>Состав плана</b><span className="text-muted text-sm ml-2">{plan.cases.length} тест-кейсов</span></div><table className="w-full border-collapse text-sm"><thead><tr className="text-left bg-slate-50 text-muted"><th className="p-4">№</th><th className="p-4">Тест-кейс</th><th className="p-4">Статус</th><th className="p-4">Приоритет</th><th className="p-4">Тип</th><th className="p-4"></th></tr></thead><tbody>{plan.cases.map((entry, index) => <tr className="border-t border-[var(--line)]" key={entry.testCase.id}><td className="p-4">{index + 1}</td><td className="p-4"><Link className="text-brand font-semibold no-underline" href={`/test-cases/${entry.testCase.id}`}>{entry.testCase.displayId}</Link><div>{entry.testCase.title}</div></td><td className="p-4">{entry.testCase.status}</td><td className="p-4">{priorityLabels[entry.testCase.priority]}</td><td className="p-4">{entry.testCase.type}</td><td className="p-4">{canManage && <button className="icon-btn text-red-600" onClick={() => remove(entry.testCase.id)}><Trash2 size={16} /></button>}</td></tr>)}{!plan.cases.length && <tr><td colSpan={6} className="p-12 text-center text-muted">Добавьте тест-кейсы в план.</td></tr>}</tbody></table></section>
    {modal && <div className="fixed inset-0 bg-slate-950/50 grid place-items-center p-4 z-50"><div className="card p-6 w-full max-w-3xl max-h-[90vh] overflow-y-auto"><div className="flex justify-between"><div><h2 className="m-0">Добавить тесты</h2><p className="text-muted text-sm">Можно совместить выбранные кейсы, папку и приоритет.</p></div><button className="icon-btn" onClick={() => setModal(false)}><X /></button></div><div className="grid grid-cols-2 gap-3 mb-4"><div><label className="text-sm font-semibold block mb-2">Целая папка</label><select className="field" value={folderId} onChange={event => setFolderId(event.target.value)}><option value="">Не выбрана</option>{folders.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></div><div><label className="text-sm font-semibold block mb-2">Все тесты по приоритету</label><select className="field" value={priority} onChange={event => setPriority(event.target.value)}><option value="">Не выбран</option>{Object.entries(priorityLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></div></div><label className="text-sm font-semibold block mb-2">Отдельные тест-кейсы</label><div className="border border-[var(--line)] rounded-xl max-h-72 overflow-y-auto">{available.map(item => <label className="flex gap-3 p-3 border-b border-[var(--line)] cursor-pointer" key={item.id}><input type="checkbox" checked={selected.includes(item.id)} onChange={event => setSelected(current => event.target.checked ? [...current, item.id] : current.filter(value => value !== item.id))} /><span><b className="text-brand">{item.displayId}</b> — {item.title}</span></label>)}{!available.length && <p className="p-4 text-muted">Все доступные тест-кейсы уже добавлены.</p>}</div><div className="flex justify-end gap-3 mt-5"><button className="btn-secondary" onClick={() => setModal(false)}>Отмена</button><button className="btn" disabled={!selected.length && !folderId && !priority} onClick={add}>Добавить</button></div></div></div>}
  </main></AppShell>;
}
