'use client';
import { useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { ArrowLeft, GitCompareArrows, TrendingDown, TrendingUp } from 'lucide-react';
import { AppShell } from '@/components/app-shell';
import { api } from '@/lib/auth';
type Label={label:string;p95Ms:number;averageMs:number;errorCount:number;sampleCount:number;throughput:number};
type Run={id:string;name:string;createdAt:string;p50Ms:number;p90Ms:number;p95Ms:number;p99Ms:number;averageMs:number;throughput:number;errorRate:number;sampleCount:number;slaPassed:boolean;project:{code:string;name:string};labels:Label[]};
const fmt=(value:number,digits=1)=>new Intl.NumberFormat('ru-RU',{maximumFractionDigits:digits}).format(value);
export default function ComparePage(){
 const[runs,setRuns]=useState<Run[]>([]),[leftId,setLeftId]=useState(''),[rightId,setRightId]=useState(''),[left,setLeft]=useState<Run|null>(null),[right,setRight]=useState<Run|null>(null),[error,setError]=useState('');
 useEffect(()=>{api<Run[]>('/performance').then(items=>{setRuns(items);setLeftId(items[1]?.id||items[0]?.id||'');setRightId(items[0]?.id||'')}).catch(e=>setError(e.message))},[]);
 useEffect(()=>{if(!leftId||!rightId){setLeft(null);setRight(null);return}Promise.all([api<Run>(`/performance/${leftId}`),api<Run>(`/performance/${rightId}`)]).then(([a,b])=>{setLeft(a);setRight(b)}).catch(e=>setError(e.message))},[leftId,rightId]);
 const labels=useMemo(()=>{if(!left||!right)return[];const old=new Map(left.labels.map(x=>[x.label,x]));return right.labels.map(current=>({current,previous:old.get(current.label)})).sort((a,b)=>delta(b.current.p95Ms,b.previous?.p95Ms)-delta(a.current.p95Ms,a.previous?.p95Ms)).slice(0,20)},[left,right]);
 return <AppShell><main className="p-7 max-w-7xl mx-auto"><Link href="/integrations/jmeter" className="inline-flex gap-2 items-center text-muted no-underline text-sm"><ArrowLeft size={16}/>Apache JMeter</Link><div className="mt-4 mb-6"><p className="text-muted text-sm m-0">Поиск регрессий между сборками</p><h1 className="text-3xl m-0 mt-1">Сравнение запусков</h1></div>{error&&<p className="p-3 rounded-xl bg-red-50 text-red-700">{error}</p>}
 <section className="card p-5"><div className="grid md:grid-cols-[1fr_auto_1fr] items-center gap-3"><RunSelect label="Базовый запуск" value={leftId} onChange={setLeftId} runs={runs}/><GitCompareArrows className="text-brand mx-auto"/><RunSelect label="Сравниваемый запуск" value={rightId} onChange={setRightId} runs={runs}/></div>{left&&right&&<div className="flex justify-end gap-3 mt-4"><Link className="text-sm text-muted no-underline hover:text-brand" href={`/integrations/jmeter/${left.id}`}>Открыть базовый</Link><Link className="text-sm text-brand no-underline font-semibold" href={`/integrations/jmeter/${right.id}`}>Открыть сравниваемый</Link></div>}</section>
 {left&&right&&<><div className="grid sm:grid-cols-2 xl:grid-cols-4 gap-4 mt-5"><DeltaCard label="P95" before={left.p95Ms} after={right.p95Ms} unit="мс" lower/><DeltaCard label="Среднее время" before={left.averageMs} after={right.averageMs} unit="мс" lower/><DeltaCard label="Throughput" before={left.throughput} after={right.throughput} unit="req/s"/><DeltaCard label="Ошибки" before={left.errorRate} after={right.errorRate} unit="%" lower/></div>
 <section className="card p-6 mt-5"><div className="flex justify-between items-center"><div><h2 className="m-0">Профиль задержек</h2><p className="text-muted text-sm mt-1">P50 / P90 / P95 / P99</p></div><span className={`px-3 py-1 rounded-full text-xs font-semibold ${right.slaPassed?'bg-green-50 text-green-700':'bg-red-50 text-red-700'}`}>SLA {right.slaPassed?'пройден':'нарушен'}</span></div><div className="grid grid-cols-4 gap-4 h-56 items-end mt-5">{(['p50Ms','p90Ms','p95Ms','p99Ms'] as const).map(key=><div className="h-full flex items-end gap-2 justify-center" key={key}><Bar value={left[key]} max={Math.max(left.p99Ms,right.p99Ms)} tone="bg-slate-300"/><Bar value={right[key]} max={Math.max(left.p99Ms,right.p99Ms)} tone="bg-indigo-500"/><span className="absolute mt-7 text-xs text-muted">{key.replace('Ms','').toUpperCase()}</span></div>)}</div><div className="flex justify-center gap-5 mt-8 text-xs"><span><i className="inline-block w-3 h-3 bg-slate-300 rounded mr-1"/>{left.name}</span><span><i className="inline-block w-3 h-3 bg-indigo-500 rounded mr-1"/>{right.name}</span></div></section>
 <section className="card overflow-hidden mt-5"><div className="p-6"><h2 className="m-0">Регрессии по операциям</h2><p className="text-muted text-sm mb-0">Сначала показаны операции с наибольшим ростом P95.</p></div><div className="overflow-x-auto"><table className="w-full text-sm border-collapse"><thead><tr className="text-left bg-slate-50 text-muted"><th className="p-4">Операция</th><th className="p-4">Было</th><th className="p-4">Стало</th><th className="p-4">Изменение P95</th><th className="p-4">Ошибки</th></tr></thead><tbody>{labels.map(({current,previous})=><tr className="border-t border-[var(--line)]" key={current.label}><td className="p-4 font-semibold">{current.label}</td><td className="p-4">{previous?`${fmt(previous.p95Ms)} мс`:'—'}</td><td className="p-4">{fmt(current.p95Ms)} мс</td><td className="p-4"><Change value={delta(current.p95Ms,previous?.p95Ms)} lower/></td><td className="p-4">{current.errorCount}/{current.sampleCount}</td></tr>)}</tbody></table></div></section></>}
 </main></AppShell>;
}
function RunSelect({label,value,onChange,runs}:{label:string;value:string;onChange:(v:string)=>void;runs:Run[]}){return <label className="text-xs text-muted">{label}<select className="field mt-1" value={value} onChange={e=>onChange(e.target.value)}>{runs.map(run=><option key={run.id} value={run.id}>{run.project.code} · {run.name} · {new Date(run.createdAt).toLocaleString('ru-RU')}</option>)}</select></label>}
function delta(after:number,before?:number){return before?Number(((after-before)/before*100).toFixed(1)):0}
function Change({value,lower=false}:{value:number;lower?:boolean}){const good=lower?value<=0:value>=0;return <span className={`inline-flex gap-1 items-center px-2 py-1 rounded-full text-xs font-semibold ${good?'bg-green-50 text-green-700':'bg-red-50 text-red-700'}`}>{value>0?<TrendingUp size={14}/>:<TrendingDown size={14}/>} {value>0?'+':''}{fmt(value)}%</span>}
function DeltaCard({label,before,after,unit,lower=false}:{label:string;before:number;after:number;unit:string;lower?:boolean}){return <article className="card p-5"><span className="text-sm text-muted">{label}</span><div className="flex items-end justify-between gap-2 mt-3"><div><b className="text-2xl">{fmt(after)} {unit}</b><span className="block text-xs text-muted mt-1">было {fmt(before)} {unit}</span></div><Change value={delta(after,before)} lower={lower}/></div></article>}
function Bar({value,max,tone}:{value:number;max:number;tone:string}){return <div className={`w-8 rounded-t-lg ${tone} relative`} style={{height:`${Math.max(8,value/Math.max(max,1)*100)}%`}}><span className="absolute -top-5 left-1/2 -translate-x-1/2 text-[10px] whitespace-nowrap">{fmt(value,0)}</span></div>}
