'use client';
import { FormEvent, useCallback, useEffect, useState } from 'react';
import Link from 'next/link';
import { Activity, ArrowLeft, CheckCircle2, FileUp, Gauge, History, ShieldCheck, Timer, XCircle } from 'lucide-react';
import { AppShell } from '@/components/app-shell';
import { api, apiUpload } from '@/lib/auth';

type Project={id:string;code:string;name:string};
type Metric={sampleCount:number;errorCount:number;errorRate:number;durationMs:number;throughput:number;averageMs:number;minMs:number;maxMs:number;p50Ms:number;p90Ms:number;p95Ms:number;p99Ms:number;receivedBytes:number};
type Label=Metric&{id?:string;label:string};
type Preview=Metric&{slaPassed:boolean;violations:string[];labels:Label[]};
type Run=Metric&{id:string;name:string;environment:string|null;build:string|null;slaPassed:boolean;createdAt:string;project:{code:string;name:string};labels:Label[]};

const initial={name:'JMeter запуск',environment:'staging',build:'',p95Ms:'1000',maxErrorRate:'1',minThroughput:'1'};
const number=(value:number,digits=0)=>new Intl.NumberFormat('ru-RU',{maximumFractionDigits:digits}).format(value);

export default function JMeterPage(){
  const[projects,setProjects]=useState<Project[]>([]),[projectId,setProjectId]=useState(''),[form,setForm]=useState(initial),[file,setFile]=useState<File|null>(null),[preview,setPreview]=useState<Preview|null>(null),[runs,setRuns]=useState<Run[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const load=useCallback(async()=>{try{const[p,r]=await Promise.all([api<{items:Project[]}>('/projects?page=1&pageSize=100&status=ACTIVE'),api<Run[]>('/performance')]);setProjects(p.items);setProjectId(value=>value||p.items[0]?.id||'');setRuns(r)}catch(reason){setError(reason instanceof Error?reason.message:'Не удалось загрузить данные')}},[]);
  useEffect(()=>{load()},[load]);
  const payload=()=>{const body=new FormData();if(file)body.append('file',file);Object.entries(form).forEach(([key,value])=>body.append(key,value));body.append('projectId',projectId);return body};
  async function inspect(){if(!file){setError('Выберите JTL или CSV файл');return}setBusy(true);setError('');try{setPreview(await apiUpload<Preview>('/performance/jmeter/preview',payload()))}catch(reason){setError(reason instanceof Error?reason.message:'Не удалось проверить файл')}finally{setBusy(false)}}
  async function save(event:FormEvent){event.preventDefault();if(!preview||!file)return;setBusy(true);setError('');try{await apiUpload('/performance/jmeter/import',payload());setPreview(null);setFile(null);await load()}catch(reason){setError(reason instanceof Error?reason.message:'Не удалось сохранить запуск')}finally{setBusy(false)}}
  return <AppShell><main className="p-7 max-w-7xl mx-auto">
    <Link href="/integrations" className="inline-flex items-center gap-2 text-sm text-muted no-underline hover:text-brand"><ArrowLeft size={16}/>Все интеграции</Link>
    <div className="flex flex-wrap justify-between items-end gap-4 mt-4 mb-6"><div><p className="text-muted text-sm m-0">Нагрузочное тестирование</p><h1 className="text-3xl m-0 mt-1">Apache JMeter</h1><p className="text-muted mt-2 mb-0">Загрузите результат JTL/CSV, проверьте SLA и сохраните агрегированные метрики.</p></div><div className="flex items-center gap-2"><Link href="/integrations/jmeter/compare" className="btn-secondary no-underline">Сравнить запуски</Link><span className="inline-flex items-center gap-2 px-3 py-2 rounded-full bg-green-50 text-green-700 text-sm font-semibold"><ShieldCheck size={17}/>Без хранения сырых запросов</span></div></div>
    {error&&<div className="p-4 mb-5 rounded-xl bg-red-50 text-red-700 flex gap-2"><XCircle size={19}/>{error}</div>}
    <form onSubmit={save} className="grid xl:grid-cols-[390px_1fr] gap-5">
      <section className="card p-6 h-fit"><div className="flex items-center gap-3"><span className="p-3 rounded-xl bg-indigo-50 text-brand"><FileUp/></span><div><h2 className="m-0 text-xl">Новый результат</h2><p className="m-0 text-xs text-muted">JTL или CSV · до 25 МБ</p></div></div>
        <label className="block text-sm font-semibold mt-5 mb-2">Проект</label><select className="field" required value={projectId} onChange={e=>setProjectId(e.target.value)}><option value="">Выберите проект</option>{projects.map(p=><option key={p.id} value={p.id}>{p.code} — {p.name}</option>)}</select>
        <label className="block text-sm font-semibold mt-4 mb-2">Название запуска</label><input className="field" required minLength={2} value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/>
        <div className="grid grid-cols-2 gap-3 mt-4"><input className="field" placeholder="Окружение" value={form.environment} onChange={e=>setForm({...form,environment:e.target.value})}/><input className="field" placeholder="Build" value={form.build} onChange={e=>setForm({...form,build:e.target.value})}/></div>
        <h3 className="text-sm mt-5 mb-2">SLA-пороги</h3><div className="grid grid-cols-3 gap-2"><label className="text-xs text-muted">P95, мс<input className="field mt-1" type="number" min="1" value={form.p95Ms} onChange={e=>setForm({...form,p95Ms:e.target.value})}/></label><label className="text-xs text-muted">Ошибки, %<input className="field mt-1" type="number" min="0" max="100" step="0.1" value={form.maxErrorRate} onChange={e=>setForm({...form,maxErrorRate:e.target.value})}/></label><label className="text-xs text-muted">Req/s<input className="field mt-1" type="number" min="0" step="0.1" value={form.minThroughput} onChange={e=>setForm({...form,minThroughput:e.target.value})}/></label></div>
        <label className="mt-5 border-2 border-dashed border-[var(--line)] rounded-xl p-5 grid place-items-center text-center cursor-pointer hover:border-indigo-400"><FileUp className="text-brand mb-2"/><b>{file?file.name:'Выберите файл'}</b><span className="text-xs text-muted mt-1">Экспорт JMeter в формате JTL/CSV</span><input className="hidden" type="file" accept=".jtl,.csv,text/csv,application/xml,text/xml" onChange={e=>{setFile(e.target.files?.[0]??null);setPreview(null)}}/></label>
        <button type="button" className="btn-secondary w-full mt-4" disabled={busy||!file} onClick={inspect}>{busy?'Анализируем…':'Проверить файл'}</button>{preview&&<button className="btn w-full mt-3" disabled={busy||!projectId}>{busy?'Сохраняем…':'Сохранить результат'}</button>}
      </section>
      <section className="space-y-5">{preview?<ResultPanel title="Предпросмотр" value={preview}/>:<article className="card p-8 min-h-64 grid place-items-center text-center"><div><Gauge size={42} className="mx-auto text-brand mb-3"/><h2 className="m-0">Метрики появятся здесь</h2><p className="text-muted max-w-lg">Файл сначала проверяется без сохранения. Вы увидите задержки, throughput, ошибки и нарушения SLA.</p></div></article>}
        <article className="card overflow-hidden"><div className="p-6 flex items-center gap-3"><History className="text-brand"/><div><h2 className="m-0 text-xl">История запусков</h2><p className="m-0 text-sm text-muted">Последние 100 результатов</p></div></div><div className="overflow-x-auto"><table className="w-full text-sm border-collapse"><thead><tr className="bg-slate-50 text-left text-muted"><th className="p-4">Запуск</th><th className="p-4">Samples</th><th className="p-4">P95</th><th className="p-4">Throughput</th><th className="p-4">Ошибки</th><th className="p-4">SLA</th></tr></thead><tbody>{runs.map(run=><tr className="border-t border-[var(--line)]" key={run.id}><td className="p-4"><b>{run.name}</b><span className="block text-xs text-muted">{run.project.code} · {run.environment||'окружение не указано'} · {new Date(run.createdAt).toLocaleString('ru-RU')}</span></td><td className="p-4">{number(run.sampleCount)}</td><td className="p-4 font-semibold">{number(run.p95Ms)} мс</td><td className="p-4">{number(run.throughput,2)} req/s</td><td className="p-4">{number(run.errorRate,2)}%</td><td className="p-4"><SlaBadge passed={run.slaPassed}/></td></tr>)}{!runs.length&&<tr><td colSpan={6} className="p-12 text-center text-muted">Сохранённых запусков пока нет</td></tr>}</tbody></table></div></article>
      </section>
    </form>
  </main></AppShell>
}

function SlaBadge({passed}:{passed:boolean}){return <span className={`inline-flex items-center gap-1 px-2.5 py-1 rounded-full text-xs font-semibold ${passed?'bg-green-50 text-green-700':'bg-red-50 text-red-700'}`}>{passed?<CheckCircle2 size={14}/>:<XCircle size={14}/>} {passed?'Пройден':'Нарушен'}</span>}
function ResultPanel({title,value}:{title:string;value:Preview}){const cards=[[Activity,'Samples',number(value.sampleCount)],[Timer,'Среднее',`${number(value.averageMs,2)} мс`],[Gauge,'P95',`${number(value.p95Ms)} мс`],[Activity,'Throughput',`${number(value.throughput,2)} req/s`]] as const;return <article className="card p-6"><div className="flex justify-between items-center gap-4"><div><p className="text-xs uppercase tracking-wider text-brand font-bold m-0">{title}</p><h2 className="mt-1 mb-0">Сводка производительности</h2></div><SlaBadge passed={value.slaPassed}/></div><div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-3 mt-5">{cards.map(([Icon,label,data])=><div className="p-4 rounded-xl bg-slate-50" key={label}><Icon size={18} className="text-brand"/><span className="block text-xs text-muted mt-3">{label}</span><b className="text-xl">{data}</b></div>)}</div>{value.violations.length>0&&<div className="mt-4 p-3 rounded-xl bg-red-50 text-red-700 text-sm">{value.violations.join(' · ')}</div>}<h3 className="text-sm mt-6">Самые медленные операции</h3><div className="space-y-3">{value.labels.slice(0,8).map(label=><div key={label.label}><div className="flex justify-between gap-4 text-sm"><span className="truncate">{label.label}</span><b>{label.p95Ms} мс · {label.errorRate}% ошибок</b></div><div className="h-2 bg-slate-100 rounded-full mt-1 overflow-hidden"><div className={`h-full rounded-full ${label.errorCount?'bg-red-500':'bg-indigo-500'}`} style={{width:`${Math.max(3,Math.min(100,label.p95Ms/Math.max(value.maxMs,1)*100))}%`}}/></div></div>)}</div></article>}
