'use client';
import { useEffect, useState } from 'react';
import { FolderKanban, ShieldCheck, UserRoundCog, Users } from 'lucide-react';
import { AppShell } from '@/components/app-shell';
import { api, session } from '@/lib/auth';
import { notify } from '@/components/toast-viewport';
type Project={id:string;code:string;name:string};
type Member={id:string;email:string;firstName:string;lastName:string;organizationRole:string;projectRole:string|null;isOwner:boolean};
const roles=[['QA_LEAD','QA Lead'],['QA_ENGINEER','QA Engineer'],['DEVELOPER','Разработчик'],['VIEWER','Наблюдатель']] as const;
export default function TeamsPage(){
  const[projects,setProjects]=useState<Project[]>([]),[projectId,setProjectId]=useState(''),[members,setMembers]=useState<Member[]>([]),[busy,setBusy]=useState(''),[error,setError]=useState('');
  const canManage=['ADMIN','QA_LEAD'].includes(session.get()?.user.role??'');
  useEffect(()=>{api<{items:Project[]}>('/projects?page=1&pageSize=100&status=ACTIVE').then(result=>{setProjects(result.items);setProjectId(result.items[0]?.id??'')}).catch(reason=>setError(reason.message))},[]);
  useEffect(()=>{if(projectId)api<Member[]>(`/projects/${projectId}/members`).then(setMembers).catch(reason=>setError(reason.message));else setMembers([])},[projectId]);
  async function assign(member:Member,role:string){setBusy(member.id);try{if(role)await api(`/projects/${projectId}/members`,{method:'PUT',body:JSON.stringify({userId:member.id,role})});else await api(`/projects/${projectId}/members/${member.id}`,{method:'DELETE'});setMembers(current=>current.map(item=>item.id===member.id?{...item,projectRole:role||null}:item));notify('Состав команды обновлён')}catch(reason){setError(reason instanceof Error?reason.message:'Ошибка сохранения')}finally{setBusy('')}}
  return <AppShell><main className="p-7 max-w-6xl mx-auto"><p className="text-muted text-sm m-0">Доступ к проектам внутри организации</p><h1 className="text-3xl mt-1 mb-6">Комана</h1>{error&&<p className="p-3 bg-red-50 text-red-700 rounded-lg">{error}</p>}<section className="card p-5 mb-5"><label className="block text-sm font-semibold mb-2">Проект</label><div className="flex gap-3 items-center"><span className="p-2.5 rounded-xl bg-indigo-50 text-brand"><FolderKanban size={20}/></span><select className="field max-w-xl" value={projectId} onChange={event=>setProjectId(event.target.value)}><option value="">Выберите проект</option>{projects.map(project=><option value={project.id} key={project.id}>{project.code} — {project.name}</option>)}</select></div></section><section className="card overflow-hidden"><div className="p-5 border-b border-[var(--line)] flex items-center gap-3"><Users className="text-brand"/><div><h2 className="m-0 text-lg">Участники проекта</h2><span className="text-xs text-muted">Назначайте роль или убирайте доступ</span></div></div>{members.map(member=><div className="flex flex-wrap justify-between items-center gap-4 p-4 border-t border-[var(--line)]" key={member.id}><div className="flex gap-3 items-center"><span className="w-10 h-10 rounded-full bg-indigo-50 text-brand grid place-items-center font-bold">{member.firstName[0]}{member.lastName[0]}</span><div><b>{member.firstName} {member.lastName}</b><span className="block text-xs text-muted">{member.email} · {member.organizationRole}</span></div>{member.isOwner&&<span className="px-2 py-1 rounded-full bg-amber-50 text-amber-700 text-[10px]">Владелец</span>}</div>{member.isOwner?<span className="flex gap-2 items-center text-sm"><ShieldCheck size={17} className="text-green-600"/>Полный доступ</span>:<select disabled={!canManage||busy===member.id} className="field w-56" value={member.projectRole??''} onChange={event=>assign(member,event.target.value)}><option value="">Без доступа</option>{roles.map(([value,label])=><option value={value} key={value}>{label}</option>)}</select>}</div>)}{!projectId&&<div className="p-14 text-center text-muted"><UserRoundCog className="mx-auto mb-3"/>Выберите проект</div>}</section></main></AppShell>;
}
