import { BadRequestException, ConflictException, Injectable, NotFoundException } from '@nestjs/common';
import { MembershipRole, Prisma } from '@prisma/client';
import * as argon2 from 'argon2';
import { PrismaService } from '../prisma/prisma.service';
import { RequestContext } from '../audit/request-context';
import { CreateOrganizationDto, CreateSystemUserDto, UpdateSystemUserDto } from './system-admin.dto';
@Injectable() export class SystemAdminService {
  constructor(private p:PrismaService){}
  stats(){return this.p.$transaction([this.p.organization.count(),this.p.user.count(),this.p.user.count({where:{isActive:true}}),this.p.auditLog.count()]).then(([organizations,users,activeUsers,auditEvents])=>({organizations,users,activeUsers,auditEvents}));}
  organizations(){return this.p.organization.findMany({orderBy:{createdAt:'desc'},select:{id:true,name:true,slug:true,createdAt:true,_count:{select:{members:true,projects:true}}}})}
  async createOrganization(actorId:string,dto:CreateOrganizationDto){try{const item=await this.p.organization.create({data:{name:dto.name.trim(),slug:dto.slug.trim().toLowerCase()}});await this.p.auditLog.create({data:{organizationId:item.id,userId:actorId,action:'ORGANIZATION_CREATED',entityType:'ORGANIZATION',entityId:item.id,metadata:{name:item.name,slug:item.slug},ipAddress:RequestContext.ip()}});return item}catch(error){if(error instanceof Prisma.PrismaClientKnownRequestError&&error.code==='P2002')throw new ConflictException('Организация с таким slug уже существует');throw error}}
  users(){return this.p.user.findMany({orderBy:{createdAt:'desc'},select:{id:true,email:true,username:true,firstName:true,lastName:true,isActive:true,isSystemAdmin:true,lastLoginAt:true,createdAt:true,memberships:{select:{role:true,organization:{select:{id:true,name:true}}}}}})}
  async createUser(actorId:string,dto:CreateSystemUserDto){if(!await this.p.organization.findUnique({where:{id:dto.organizationId}}))throw new NotFoundException('Организация не найдена');try{const user=await this.p.user.create({data:{email:dto.email.trim().toLowerCase(),username:dto.username.trim().toLowerCase(),firstName:dto.firstName.trim(),lastName:dto.lastName.trim(),passwordHash:await argon2.hash(dto.password),memberships:{create:{organizationId:dto.organizationId,role:dto.role}}}});await this.p.auditLog.create({data:{organizationId:dto.organizationId,userId:actorId,action:'SYSTEM_USER_CREATED',entityType:'USER',entityId:user.id,metadata:{email:user.email,role:dto.role},ipAddress:RequestContext.ip()}});return{success:true,id:user.id}}catch(error){if(error instanceof Prisma.PrismaClientKnownRequestError&&error.code==='P2002')throw new ConflictException('Email или логин уже занят');throw error}}
  async updateUser(actorId:string,id:string,dto:UpdateSystemUserDto){const user=await this.p.user.findUnique({where:{id},include:{memberships:true},});if(!user)throw new NotFoundException('Пользователь не найден');if(user.isSystemAdmin&&dto.isActive===false)throw new BadRequestException('Системного администратора нельзя отключить');const current=user.memberships[0];const organizationId=dto.organizationId??current?.organizationId;if(!organizationId)throw new BadRequestException('Выберите организацию');if(dto.organizationId&&dto.organizationId!==current?.organizationId&&await this.p.project.count({where:{ownerId:id}}))throw new BadRequestException('Сначала передайте проекты другому владельцу');await this.p.$transaction(async tx=>{await tx.user.update({where:{id},data:{firstName:dto.firstName?.trim(),lastName:dto.lastName?.trim(),isActive:dto.isActive}});if(dto.organizationId||dto.role){await tx.organizationMember.deleteMany({where:{userId:id}});await tx.organizationMember.create({data:{userId:id,organizationId,role:dto.role??current?.role??MembershipRole.VIEWER}})}if(dto.isActive===false)await tx.refreshToken.updateMany({where:{userId:id,revokedAt:null},data:{revokedAt:new Date()}});await tx.auditLog.create({data:{organizationId,userId:actorId,action:'SYSTEM_USER_UPDATED',entityType:'USER',entityId:id,metadata:{changes:dto as Prisma.InputJsonObject},ipAddress:RequestContext.ip()}})});return{success:true}}
  async disableUser(actorId:string,id:string){return this.updateUser(actorId,id,{isActive:false})}
  audit(){return this.p.auditLog.findMany({take:300,orderBy:{createdAt:'desc'},include:{user:{select:{firstName:true,lastName:true,email:true}},organization:{select:{name:true}}}})}
}
