'use client';
import { useCallback, useEffect, useState } from 'react';
import { Download, History, Search } from 'lucide-react';
import { AppShell } from '@/components/app-shell';
import { api } from '@/lib/auth';

type Event = { id:string; action:string; entityType:string|null; entityId:string|null; metadata:Record<string,unknown>|null; ipAddress:string|null; createdAt:string; user:{firstName:string;lastName:string;email:string}|null };
type Data = { items:Event[]; meta:{total:number} };
const labels:Record<string,string> = { LOGIN_SUCCESS:'Успешный вход', USER_CREATED:'Пользователь создан', USER_UPDATED:'Пользователь изменён', PASSWORD_RESET:'Пароль сброшен', PROFILE_UPDATED:'Профиль изменён', PASSWORD_CHANGED:'Пароль изменён', AUTOMATION_KEY_CREATED:'API-ключ создан', AUTOMATION_KEY_REVOKED:'API-ключ отозван', PROJECT_MEMBER_UPDATED:'Роль в проекте изменена', PROJECT_MEMBER_REMOVED:'Участник удалён из проекта', DEFECT_CREATED:'Дефект создан', DEFECT_UPDATED:'Дефект изменён', REPORT_QUEUED:'Отчёт добавлен в очередь' };

export default function Audit() {
  const [data,setData]=useState<Data>({items:[],meta:{total:0}}), [search,setSearch]=useState(''), [action,setAction]=useState(''), [error,setError]=useState('');
  const load=useCallback(()=>{const p=new URLSearchParams({page:'1',pageSize:'100'});if(search)p.set('search',search);if(action)p.set('action',action);api<Data>(`/users/audit?${p}`).then(setData).catch((e)=>setError(e.message));},[search,action]);
  useEffect(()=>{const timer=setTimeout(load,250);return()=>clearTimeout(timer);},[load]);
  function csv(){const rows=[['Дата','Пользователь','IP-адрес','Действие','Тип','ID'],...data.items.map((event)=>[new Date(event.createdAt).toLocaleString('ru-RU'),event.user?`${event.user.firstName} ${event.user.lastName}`:'Система',event.ipAddress??'',labels[event.action]??event.action,event.entityType??'',event.entityId??''])];const blob=new Blob(['\ufeff'+rows.map((row)=>row.map((value)=>`"${String(value).replaceAll('"','""')}"`).join(';')).join('\n')],{type:'text/csv'}),url=URL.createObjectURL(blob),anchor=document.createElement('a');anchor.href=url;anchor.download='audit-log.csv';anchor.click();URL.revokeObjectURL(url);}
  return <AppShell><main className="p-7 max-w-7xl mx-auto"><div className="flex justify-between items-end"><div><p className="text-muted text-sm m-0">Безопасность и отслеживание действий</p><h1 className="text-3xl mt-1">Журнал аудита</h1></div><button className="btn-secondary flex gap-2" onClick={csv}><Download size={17}/>Экспорт CSV</button></div>{error&&<p className="p-3 bg-red-50 text-red-700 rounded">{error}</p>}<section className="card overflow-hidden"><div className="p-4 flex gap-3"><div className="relative flex-1"><Search className="absolute left-3 top-3 text-muted" size={18}/><input className="field pl-10" placeholder="Пользователь или email" value={search} onChange={(e)=>setSearch(e.target.value)}/></div><select className="field max-w-72" value={action} onChange={(e)=>setAction(e.target.value)}><option value="">Все действия</option>{Object.entries(labels).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></div><div className="overflow-x-auto"><table className="w-full text-sm border-collapse"><thead><tr className="bg-slate-50 text-left text-muted"><th className="p-4">Дата</th><th className="p-4">Пользователь</th><th className="p-4">IP-адрес</th><th className="p-4">Действие</th><th className="p-4">Объект</th><th className="p-4">Изменения</th></tr></thead><tbody>{data.items.map((event)=><tr className="border-t border-[var(--line)]" key={event.id}><td className="p-4 whitespace-nowrap">{new Date(event.createdAt).toLocaleString('ru-RU')}</td><td className="p-4">{event.user?`${event.user.firstName} ${event.user.lastName}`:'Система'}<span className="block text-xs text-muted">{event.user?.email}</span></td><td className="p-4"><code className="text-xs">{event.ipAddress??'—'}</code></td><td className="p-4 font-semibold">{labels[event.action]??event.action}</td><td className="p-4">{event.entityType??'—'}<span className="block text-[10px] text-muted">{event.entityId}</span></td><td className="p-4 max-w-sm"><code className="text-[10px] whitespace-pre-wrap">{event.metadata?JSON.stringify(event.metadata,null,1):'—'}</code></td></tr>)}{!data.items.length&&<tr><td colSpan={6} className="p-14 text-center text-muted"><History className="mx-auto mb-2"/>Событий нет</td></tr>}</tbody></table></div></section></main></AppShell>;
}
